workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

default:
  image: node:16-bullseye-slim

cache:
  key: yarn
  policy: pull-push
  paths:
    - node_modules/

stages:
  - install
  - static-analysis
  - test

install:
  stage: install
  script:
    - yarn install

static-analysis:
  stage: static-analysis
  script:
    - yarn prettier
    - yarn eslint
    - yarn typecheck

test:
  stage: test
  script:
    - yarn test
