name: Validate Changelog

on:
  pull_request:
    branches: [main]

jobs:
  validate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changelog changes
        id: check-changelog
        run: |
          # Get the list of changed files in the PR
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          CHANGELOG_CHANGES=$(echo "$CHANGED_FILES" | grep "^changelogs/" || true)

          if [ -z "$CHANGELOG_CHANGES" ]; then
            echo "No changelog files were changed in this PR"
            echo "changelog_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Found changelog changes:"
            echo "$CHANGELOG_CHANGES"
            echo "changelog_changed=true" >> $GITHUB_OUTPUT
            echo "changed_files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGELOG_CHANGES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Validate changelog files
        if: steps.check-changelog.outputs.changelog_changed == 'true'
        run: |
          # Read the changed files from the previous step
          CHANGED_FILES="${{ steps.check-changelog.outputs.changed_files }}"

          echo "Validating changelog files..."
          VALIDATION_FAILED=false

          for file in $CHANGED_FILES; do
            echo "Checking file: $file"
            
            # Check if file exists and is readable
            if [ ! -f "$file" ]; then
              echo "Error: File $file does not exist"
              VALIDATION_FAILED=true
              continue
            fi
            
            # Check for 'public: true' (case sensitive, exact match)
            if ! grep -q "^public: true$" "$file"; then
              echo "Error: File $file does not have public: true"
              echo "Current public line: $(grep '^public:' "$file" || echo 'not found')"
              VALIDATION_FAILED=true
            else
              echo "File $file is valid (public: true)"
            fi
          done

          if [ "$VALIDATION_FAILED" = true ]; then
            echo "Changelog validation failed"
            exit 1
          else
            echo "All changelog files are valid"
          fi

      - name: Fail if no changelog changes
        if: steps.check-changelog.outputs.changelog_changed == 'false'
        run: |
          echo "This PR does not include any changelog changes"
          echo "Please add at least one changelog file in the /changelogs directory"
          echo "Each changelog file must have 'public: true' set"
          exit 1
